#服务端口
server:
  port: 8888
  servlet:
    encoding:
      enabled: true
      charset: utf-8
      force: true
#服务名
spring:
  application:
    name: springboot-shardingsphere
  main:
    allow-bean-definition-overriding: true
  #shardingsphere相关配置
  shardingsphere:
    datasource:
      names: ds0
      ds0: #配置主库的数据源信息
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.135.128:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    sharding:
      tables:
        file_test:
          actual-data-nodes: ds0.file_test_${200001..209912}
          table-strategy:
            standard:
              sharding-column: create_time
              #精确分片算法类名称，用于=和IN。。该类需实现 PreciseShardingAlgorithm 接口并提供无参数的构造器
              precise-algorithm-className: com.guo.sharding.config.DatabaseShardingAlgorithm
              #范围分片算法类名称，用于BETWEEN，可选。。该类需实现RangeShardingAlgorithm接口并提供无参数的构造器
          keyGenerator:
            type: SNOWFLAKE
            column: id
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        max-active: 20
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 2000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 900000
        # 用来测试连接是否可用的SQL语句,默认值每种数据库都不相同,这是mysql
        validation-query: SELECT 1 FROM DUAL
        # 应用向连接池申请连接，并且testOnBorrow为false时，连接池将会判断连接是否处于空闲状态，如果是，则验证这条连接是否可用
        test-while-idle: true
        # 如果为true，默认是false，应用向连接池申请连接时，连接池会判断这条连接是否是可用的
        test-on-borrow: false
        # 如果为true（默认false），当应用使用完连接，连接池回收连接的时候会判断该连接是否还可用
        test-on-return: false
        # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle
        pool-prepared-statements: true
        # 要启用PSCache，必须配置大于0，当大于0时， poolPreparedStatements自动触发修改为true，
        # 在Druid中，不会存在Oracle下PSCache占用内存过多的问题，
        # 可以把这个数值配置大一些，比如说100
        max-pool-prepared-statement-per-connection-size: 20
        # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作
        keep-alive: true
        # Spring 监控，利用aop 对指定接口的执行时间，jdbc数进行记录
        aop-patterns: "com.guo.sharding.mapper.*"
        ########### 启用内置过滤器（第一个 stat必须，否则监控不到SQL）##########
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        # 多数据源配置
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.135.128:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: Root123!
        slave1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.135.130:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
          username: root
          password: Root123!

  redis:
    host: 192.168.135.129 #Redis服务器地址
    port: 6379 #Redis服务器连接端口
    database: 0 #Redis数据库索引（默认为0）
    timeout: 1800000 #连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 20 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 #连接池中的最大空闲连接
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        min-idle: 0 #连接池中的最小空闲连接
    cluster:
      expire-seconds: 120 #设置key的生存时间，当key过期时，它会被自动删除；
      command-timeout: 101000 #设置命令的执行时间，如果超过这个时间，则报错;
      nodes:
        192.168.135.129:6379,
        192.168.135.129:6380,
        192.168.135.129:6381,
        192.168.135.129:6389,
        192.168.135.129:6390,
        192.168.135.129:6391
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-enums-package: com.guo.sharding.entity
  configuration:
    cache-enabled: false
    default-executor-type: reuse
    jdbc-type-for-null: 'null'
    lazy-loading-enabled: true
    local-cache-scope: session
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler   # EnumTypeHandler 配置为它时不能识别默认GenderEnum
  mapper-locations: classpath:mapper/*Mapper.xml